" ------------------------
" => General settings    |
"-------------------------

set nocompatible
set encoding=utf-8

execute pathogen#infect()
filetype plugin indent on
syntax on

" Always displaying status line
set laststatus=2

" Performance stuff
set re=1
set lazyredraw

" Indentation configurations
set modelines=0
set tabstop=2
set shiftwidth=2
set expandtab

" Folding config
set foldmethod=indent
set foldlevel=20

" Show row numbers
set number
set numberwidth=1

" Cursor line highlight
set cursorline
set cursorcolumn
set cc=80

set backspace=indent,eol,start

" Real-time highlight when searching with / or ?
set hlsearch
set incsearch

if (empty($TMUX))
  if (has("nvim"))
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  if (has("termguicolors"))
    set termguicolors
  endif
endif

" Colorscheme
set background=dark        " for the light version
let g:one_allow_italics = 1 " I love italic for comments
colorscheme one
set t_Co=256

" let base16colorspace=256

"-------------------------
" => Keybindings         |
"-------------------------

let mapleader = "\<Space>"

" enter normal mode with double
inoremap jj <ESC>

" switching tabs by shift+(h/l)
nnoremap H gT
nnoremap L gt

" macro manage
nnoremap Q @q
vnoremap Q :norm @q<CR>

" discarding highlight from hlsearch
nnoremap <F3> :noh<CR>

" |--> Keybindings related to plugins

map <C-n> :NERDTreeToggle<CR>

" Remaping NERDcommenter
map <C-_> <leader>c<Space>

" Easymotion
map  <Leader>s <Plug>(easymotion-bd-f)
nmap <Leader>s <Plug>(easymotion-overwin-f)

" Syntastic
nmap <silent> <leader>x :SyntasticToggleMode<CR>

" CtrlP
nnoremap <C-t> :CtrlP<CR>

" UndoTree
nnoremap <F5> :UndotreeToggle<cr>

" Emmet
nmap ,, <C-Y>,
imap ,, <C-Y>,
nnoremap <leader>e :Emmet<Space>

" Autoformat
nnoremap <leader>b :Neoformat<CR>

" Multicursor
let g:multi_cursor_start_key='<F2>'

"-------------------------
" => Plugins settings    |
"-------------------------

" |--> NerdTREE
autocmd VimEnter * NERDTree
let g:NERDTreeWinSize = 27
autocmd VimEnter * wincmd p
autocmd StdinReadPre * let s:std_in=1
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" |--> NerdCommenter
let g:NERDSpaceDelims = 1
let g:NERDCommentEmptyLines = 1
let g:NERDCompactSexyComs = 1
let g:NERDDefaultAlign = 'left'

" |--> GitGutter
let g:gitgutter_realtime = 1

" |--> Indent Guides
" autocmd VimEnter * IndentGuidesEnable
" let g:indent_guides_start_level = 2
" let g:indent_guides_guide_size = 1
" let g:indent_guides_exclude_filetypes = ['nerdtree']"

" |--> indentLine
let g:indentLine_char = '│'
let g:indentLine_setColors = 0

" |--> Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_aggregate_errors = 1
let g:syntastic_loc_list_height=3
let g:syntastic_mode_map = { 'mode': 'passive' }
let g:syntastic_ruby_checkers = ['rubocop', 'mri', 'jruby']
let g:syntastic_go_checkers = ['go', 'golint', 'govet', 'errcheck']
let g:syntastic_javascript_checkers = ['eslint']

" |--> Closetag
let g:closetag_filenames = "*.html,*.erb,*.vue"

" |--> Html5 plugin indentations in Vue files
autocmd BufRead,BufNewFile *.vue setlocal filetype=html.javascript.css.vue
" autocmd BufWritePre *.vue :/<script>/+1,/<\/script>/-1 !standard --fix --stdin

let g:neoformat_javascript_prettier = {
      \ 'exe': 'prettier',
      \ 'args': ['--single-quote', '--trailing-comma es5'],
      \ 'stdin': 1,
      \}
let g:neoformat_enabled_javascript = ['prettier']

let g:neoformat_python_autopep8 = {
            \ 'args': ['-s 4', '-E'],
            \ 'replace': 1,
            \ 'stdin': 1,
            \ 'no_append': 1,
            \ }
let g:neoformat_enabled_python = ['autopep8', 'yapf']

" |--> Python mode
let g:pymode_python = 'python3'

" |--> vim-go config
let g:go_fmt_command = "goimports"
